# Generated by Django 5.1.5 on 2025-02-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikey',
            name='key_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
